# Generated by Django 4.1 on 2022-09-04 21:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('spotify_token', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=250)),
                ('spotify_data', jsonfield.fields.JSONField()),
                ('classification', models.IntegerField(default=0)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critic.spotifyuser')),
            ],
        ),
    ]
