# Generated by Django 4.1 on 2022-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0002_trackprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackprediction',
            name='classification_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
